application: mynotes-970
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: notes.app

libraries:
- name: jinja2
  version: latest
